### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by webcaetano** [webcaetano/webcaetano.github.io#1]
- [x] Cover
  - [x] Main Links
  - [x] Footer (social media, github)
- [x] My Articles
  - [x] About
  - [x] Contact
  - [x] Portfolio
- [x] Front End Design
  - [x] Cover 
  - [x] Posts Design
- [x] Static Blog + Markdown + Friendly Link
- [x] Build

**Comment by webcaetano** [comment]
- [x] Add Emojis to Markdown :tada:
